### PR TITLE
Extract alarm results from action results

### PR DESCRIPTION
**Pull request by ryo-ma**
I have temporarily fixed error of results. 
To my mind, The results should be supported to serializer in the Meteoroid core. Then, should fix fields length of results.

### CODE REVIEW

**Comment by YujiAzama** [comment]
@ryo-ma Can you register issue about this bug?

**Review by hide-hayashi — COMMENTED** [review]
Thank you for fix result from action results.

The error occurs as following
 Row has incorrect number of values, (actual) 6!=9 (expected)

So, your fixed cords appending only max_len result.
Please tell me why you can skip not  maximum length result in data.

**Comment by ryo-ma** [comment]
I made a mistake.

**Comment by ryo-ma** [comment]
Updated.

@hhayashiool The key length and value length have to be the same in the clif. The results of general function have 9 keys.
Therefore, I skipped the schedule-trigger results that have 6 keys.

**Comment by ryo-ma** [comment]
@YujiAzama I posted to issue in Meteoroid core.
https://github.com/OkinawaOpenLaboratory/fiware-meteoroid/issues/18

**Comment by ryo-ma** [comment]
https://github.com/OkinawaOpenLaboratory/fiware-meteoroid/pull/19

**Pull request closed without merging**
